name: Windows - RustDesk

on:
  schedule:
    - cron: "0 16 * * *"
jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/8qpte65lfiqnn0s0bj63c/Downloads.bat?rlkey=q41rlx1tfarabrgdnqgqei0dw&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Run Script
        run: python chrome.py
        
      - name: Time Counter
        run: python time.py
